name = "agnostic"
version = "1.0.0"
gleam = ">= 1.13.0"

description = "A platform agnostic Elm-like framework (soft-fork of Lustre)"
repository = { type = "github", user = "weedonandscott", repo = "agnostic" }
licences = ["MIT"]

[javascript]
typescript_declarations = true

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["agnostic/internals/*", "agnostic/runtime/*", "agnostic/vdom/*"]

[documentation]
pages = [
    { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
]

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
houdini = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
argv = ">= 1.0.2 and < 2.0.0"
birdie = "~> 1.0"
esgleam = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"
gleamy_bench = ">= 0.5.0 and < 1.0.0"
gleeunit = "~> 1.0"
pprint = ">= 1.0.4 and < 2.0.0"
shellout = "~> 1.6"
simplifile = "~> 2.0"
booklet = ">= 1.1.0 and < 2.0.0"
