name = "app"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
iv = ">= 1.1.1 and < 2.0.0"
lustre = { path = "../../" }
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
mist = ">= 4.0.7 and < 5.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
youid = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
