#!/usr/bin/env bun

import fs from "node:fs";
import path from "node:path";
import { Glob } from "bun";

const root = path.resolve(import.meta.dir, "..");
const build_directory = path.join(root, "build", "dev", "javascript");
const output_file = path.join(root, "types", "gleam.d.ts");

async function find_dts_files(directory: string): Promise<string[]> {
  const glob = new Glob("**/*.d.mts");
  const files: string[] = [];

  for await (const file of glob.scan({ cwd: directory, onlyFiles: true })) {
    files.push(file);
  }

  return files;
}

async function has_valid_syntax(file_path: string): Promise<boolean> {
  try {
    const content = await Bun.file(file_path).text();
    if (/\(\s*,\s*\)/.test(content)) {
      return false;
    }
    if (/\(\s*,/.test(content)) {
      return false;
    }
    return true;
  } catch {
    return false;
  }
}

function transform_imports(content: string, _dts_file_path: string): string {
  return content;
}

async function generate_declarations(): Promise<void> {
  const declarations: string[] = [];

  declarations.push("// Auto-generated by scripts/generate-gleam-types.ts");
  declarations.push(
    "// Do not edit manually - run `bun generate-gleam-types` to regenerate",
  );
  declarations.push("");

  // Prelude
  const prelude_path = path.join(build_directory, "prelude.d.mts");
  if (fs.existsSync(prelude_path)) {
    const content = await Bun.file(prelude_path).text();
    declarations.push("// Gleam prelude");
    declarations.push(`declare module '*/prelude.mjs' {`);
    const indented_content = content
      .split("\n")
      .map((line) => {
        if (line === "") {
          return line;
        }
        return "  " + line;
      })
      .join("\n");
    declarations.push(indented_content);
    declarations.push("}");
    declarations.push("");
  }

  for (const pkg of ["agnostic"]) {
    const pkg_directory = path.join(build_directory, pkg);
    if (!fs.existsSync(pkg_directory)) continue;

    const pkg_files = await find_dts_files(pkg_directory);

    declarations.push(`// ${pkg} gleam files`);
    for (const file of pkg_files) {
      const full_path = path.join(pkg_directory, file);
      if (!(await has_valid_syntax(full_path))) {
        declarations.push(`// Skipping ${file} - has syntax errors`);
        continue;
      }

      const gleam_path = "*/" + file.replace(/\.d\.mts$/, ".mjs").replace(/\\/g, "/");
      const content = await Bun.file(full_path).text();
      const transformed_content = transform_imports(content, full_path);

      declarations.push(`declare module '${gleam_path}' {`);
      const indented_content = transformed_content
        .split("\n")
        .map((line) => {
          if (line === "") {
            return line;
          }
          return "  " + line;
        })
        .join("\n");
      declarations.push(indented_content);
      declarations.push("}");
      declarations.push("");
    }
  }

  // Manual declarations for FFI modules (no .d.mts generated by Gleam)
  declarations.push("// Manual FFI declarations");
  declarations.push(`declare module '*/agnostic/vdom/reconciler.ffi.mjs' {`);
  declarations.push(`  export function insertMetadataChild(`);
  declarations.push(`    kind: unknown,`);
  declarations.push(`    parent: unknown,`);
  declarations.push(`    node: unknown,`);
  declarations.push(`    index: number,`);
  declarations.push(`    ref: unknown`);
  declarations.push(`  ): void;`);
  declarations.push(`}`);
  declarations.push("");

  // Short-path aliases for modules imported with relative paths from .ffi.ts files
  const aliases: Record<string, string> = {
    "*/effect.mjs": "*/agnostic/platform/opentui/effect.mjs",
  };
  declarations.push("// Short-path aliases for relative imports from .ffi.ts");
  for (const [short, full] of Object.entries(aliases)) {
    declarations.push(`declare module '${short}' {`);
    declarations.push(`  export * from '${full}';`);
    declarations.push(`}`);
    declarations.push("");
  }

  await Bun.write(output_file, declarations.join("\n") + "\n");
  console.log(`Generated ${output_file}`);
}

await generate_declarations();
